// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:4b42b040-5eeb-48d1-b88d-00302a02eb11",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_A8iKYzGaD",
    "aws_user_pools_web_client_id": "6cn3u5tasamb8il7lmnsvc7jse",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://v334un7sefahnjwpg2lscdds5e.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-fakeApiId123456"
};


export default awsmobile;
